// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.akira;

public final class HelloWorldObj_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("java.lang.String sayHelloWorld()")
    };
    
    private static final long interfaceHash = 6265719201901276499L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	com.akira.HelloWorldObj server = (com.akira.HelloWorldObj) obj;
	switch (opnum) {
	case 0: // sayHelloWorld()
	{
	    call.releaseInputStream();
	    java.lang.String $result = server.sayHelloWorld();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
