// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.akira;

public final class HelloWorldObj_Stub
    extends java.rmi.server.RemoteStub
    implements com.akira.HelloWorld
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_sayHelloWorld_0;
    
    static {
	try {
	    $method_sayHelloWorld_0 = com.akira.HelloWorld.class.getMethod("sayHelloWorld", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public HelloWorldObj_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of sayHelloWorld()
    public java.lang.String sayHelloWorld()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHelloWorld_0, null, 1915820886661313433L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
