<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="BeforeTunning.xsd"/>
      <rootElement name="BeforeTunningProcessRequest" namespace="http://xmlns.oracle.com/BeforeTunning"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="BeforeTunning.xsd"/>
      <rootElement name="BeforeTunningProcessResponse" namespace="http://xmlns.oracle.com/BeforeTunning"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [FRI MAR 19 18:53:27 JST 2010]. -->
?>
<xsl:stylesheet version="1.0" xmlns:ns1="http://xmlns.oracle.com/BeforeTunning"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                exclude-result-prefixes="xsl ns1 ns0 xref xp20 bpws ora ehdr orcl ids hwf">
  <xsl:template match="/">
    <ns1:BeforeTunningProcessResponse>
      <xsl:for-each select="/ns1:BeforeTunningProcessRequest/ns1:item">
        <ns1:item>
          <ns1:key>
            <xsl:value-of select="ns1:key"/>
          </ns1:key>
          <ns1:value>
            <xsl:value-of select='orcl:lookup-xml("http://soad01.olympus.co.jp/soa/InterfaceComponents/ModelLibrary/Mono/Common/V1/PDMObjectTypeMap.xml","/ObjectTypeList/ObjectType","Code","Value",ns1:key)'/>
          </ns1:value>
        </ns1:item>
      </xsl:for-each>
    </ns1:BeforeTunningProcessResponse>
  </xsl:template>
</xsl:stylesheet>
