USE SAMPLE;

SHOW TABLES;

DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS REVIEWER;
DROP TABLE IF EXISTS ARTIST;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS KODO_SEQUENCE_TABLE;

SHOW TABLES;
