SET  LINESIZE     160
SET  PAGESIZE     0
SET  LONG         100000
SET  HEADING      OFF
SET  VERIFY       OFF
SET  FEED         OFF
SET  PAUSE        OFF
SET  ECHO         OFF
SET  TERMOUT      OFF
COL  TEXT         FOR A160
SPOOL $VIEW_NAME$.SQL
SELECT 'CREATE OR REPLACE VIEW PRODUCE.$VIEW_NAME$ (' FROM DUAL;
SELECT '        "' || COLUMN_NAME || '"' || NVL2(LEAD(COLUMN_ID) OVER (ORDER BY COLUMN_ID), ',', ') AS') FROM USER_TAB_COLUMNS WHERE TABLE_NAME = '$VIEW_NAME$';
SELECT TEXT FROM USER_VIEWS WHERE VIEW_NAME = UPPER('$VIEW_NAME$');
SELECT '/' FROM DUAL;
SPOOL OFF
QUIT